# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "ğŸ’¥ Breaking Changes"
      labels:
        - breaking-change
    - title: "ğŸš€ New Features"
      labels:
        - enhancement
    - title: "ğŸš§ Testing"
      labels:
        - tests
    - title: "ğŸ› Bug Fixes"
      labels:
        - bug
    - title: "âœ… Other Changes"
      labels:
        - "*"
